database:
  servers:
    - url: "postgresql://postgres:postgres@localhost:5433/bakery"
      read_only: false
    - url: "postgresql://postgres:postgres@localhost:5433/bakery"
      read_only: true

graphql:
  listen: "127.0.0.1:8001"
  endpoint: "http://localhost:8001"
  subscription_endpoint: "ws://localhost:8001/ws"

redis:
  url: "redis://localhost:6379"

jwt:
  public_key: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUk3AlUwj8R9b2q3W07svyICe/yRY
    o6UOGrivZUziFP8d1iwSYpuWAtAzYxvrdFFy+uL8gM5+XriNl0sKASctrA==
    -----END PUBLIC KEY-----
  private_key: |-
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgEBdo+Y8mOs634Jv7
    j6CTcEnsiEAm5Ac5qdxYFlP1gD+hRANCAARSTcCVTCPxH1vardbTuy/IgJ7/JFij
    pQ4auK9lTOIU/x3WLBJim5YC0DNjG+t0UXL64vyAzn5euI2XSwoBJy2s
    -----END PRIVATE KEY-----