database:
  servers:
    - url: "postgresql://postgres:postgres@localhost:5433/bakery"
      read_only: false
    - url: "postgresql://postgres:postgres@localhost:5433/bakery"
      read_only: true

graphql:
  listen: "127.0.0.1:8001"
  endpoint: "http://localhost:8001"
  subscription_endpoint: "ws://localhost:8001/ws"

redis:
  url: "redis://localhost:6379"

jwt:
  public_key: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqRvb2xxsTds9Ff09vOc5
xnOTzSWDhmQrAEOYeyqmtinhGvjD2C/CU0H4QWxjJiIN54closrzslKNuNLUyXkx
fZg4L0QhWfCrlFY50khVHCqlBkVsI7oTks6/aAEUVePMd/qCkwxR/KBGr1TumeJW
U1WPMeGl/jzzmo8GEruGLw98xl+G8vD2uxKh96fo9Kibf5llH/xonXgO/9HZt1am
nGdV3K0SKbPHkctOMDbRs646n3zUL6Vi5Zze5R+YoO5TlUR/lypEVXp6xA0j4JL+
5HHdzF/VZtVcHrTWL0u7iBNR/B6SOhmS2/k6nOEl+8wzxC5T2zCoXjR09UdOZIDA
aQIDAQAB
-----END PUBLIC KEY-----"
  private_key: "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpG9vbHGxN2z0V
/T285znGc5PNJYOGZCsAQ5h7Kqa2KeEa+MPYL8JTQfhBbGMmIg3nhyWiyvOyUo24
0tTJeTF9mDgvRCFZ8KuUVjnSSFUcKqUGRWwjuhOSzr9oARRV48x3+oKTDFH8oEav
VO6Z4lZTVY8x4aX+PPOajwYSu4YvD3zGX4by8Pa7EqH3p+j0qJt/mWUf/GideA7/
0dm3VqacZ1XcrRIps8eRy04wNtGzrjqffNQvpWLlnN7lH5ig7lOVRH+XKkRVenrE
DSPgkv7kcd3MX9Vm1VwetNYvS7uIE1H8HpI6GZLb+Tqc4SX7zDPELlPbMKheNHT1
R05kgMBpAgMBAAECggEAE/TbrzHdfhqfTNcD0CUhZlABYzZIHTX49SEE/5P69Ihg
rkQpKHwKXLTuTRozYS6noWkLgfidZa/kValbvyL0OjQafUl2/hwuw2ShkjVDBf3q
V6Edr+Gnqa2IXQezlKc7W/VOL3hGvJ9VeB93wOU69r6kFWjho+0hel3ig5dpsGfc
VXFBwQ/FkASlZ6MXmCAMKjnIXtQZ38qWxwhF9Bjc4nyw2b5sLpaayrmqPSZlBUm/
zCpQhoT211cDNuz49f3JrvfNYxF2IaAdG7HAkPYsCMvESDhRwnavtpJ6EgyXm6G5
CXVft6Lo2F1HG+R+F+fWA0Bfxq/Z8Wh6QXt2VLIUYQKBgQDYu5QoefS+4nahPRSK
VvKRRLQjFX3qUvdaEBiSKYySfJ2LcTZvJPfDvY48hbIlXi7Xm7s3VjSsx4KpEqBB
v/L9VaQdH/18Al8T+dqa+Yjj8i6QJtqEFg9uRCX916Y/ebcz5XgHBp05W5Sk5uv6
LQLd1ai0Zw9XmyFfOcrqNjooTQKBgQDHv2ehZDa4JqdXpD/ZYQQ2xkAy3FYWW9UH
PK5S3KyWKjIlTLQ004VacUCtm+7ar3CFkxQCo6K25uU7HtI6HZjoEJMRAl4x8h07
GniRJ23FctUK6ox30ZX+XMT59IV0Xo03eHt5XAvbnGRWYjn0Ylnr+UzJyYrAzIcD
qShSbwHGjQKBgCnrfiimDhStsMxXCBYJ4zj91OnESmp8SaN94YLDzpC20bIa37B3
sgSGMXC7W02m/eBuGrQFVILmw/r3w090VQdy/R81BM5rlwBCH2pCQZv1R9RR74oE
yk9FlyOWBm3YmPrMs36IZPinIgUTNSlac2d83/ikxm7nbnkAsKLEglMxAoGAHcfY
wIQ7cEs7CeMQLe27/hqiubKGF0FLyo9ugiYqiRzzawI7n+Clci2OchPckbg0c4XR
Ju+Us+ZK6PyYZVfCU18dPhz3REUPvJ8euK2DPTv4rW740GhsD4dvSsD9ILN0JIAP
ELH7hpuTjhmJAHmlZHw/yZoF2OblflM7EsdAIYUCgYEAxndMR8ZpIWkD0DTbeBJv
UvMirnOVGhzWFIH7KqlAd5U7AI3Vzym5o4ojR9iftORz3viuiCfT2HnekHbIxsKo
VRz6Sjy416wWK1j/vsZOXpHHsQ+IDPIVnC4Ugg04roi+bcIzB/nyU94bTvLCweht
hLOHTGp8NEZcFP0dBU1jvDA=
-----END PRIVATE KEY-----"