version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bakery
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data