//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use async_graphql::Enum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "event_message"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub event_type: String,
    pub status: EventMessageStatus,
    pub payload: Json,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    EventType,
    Status,
    Payload,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::EventType => ColumnType::String(None).def(),
            Self::Status => ColumnType::String(None).def(),
            Self::Payload => ColumnType::Json.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Enum, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(None)")]
pub enum EventMessageType {
    #[sea_orm(string_value = "ORDER_CREATED")]
    OrderCreated,
    #[sea_orm(string_value = "ORDER_UPDATED")]
    OrderUpdated,
    #[sea_orm(string_value = "ORDER_DELETED")]
    OrderDeleted,
    #[sea_orm(string_value = "PRODUCT_CREATED")]
    ProductCreated,
    #[sea_orm(string_value = "PRODUCT_UPDATED")]
    ProductUpdated,
    #[sea_orm(string_value = "PRODUCT_DELETED")]
    ProductDeleted,
    #[sea_orm(string_value = "PRODUCT_STOCK_UPDATED")]
    ProductStockUpdated,
    #[sea_orm(string_value = "BAKERY_CREATED")]
    BakeryCreated,
    #[sea_orm(string_value = "BAKERY_UPDATED")]
    BakeryUpdated,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Enum, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(None)")]
pub enum EventMessageStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "PROCESSED")]
    Processed,
    #[sea_orm(string_value = "FAILED")]
    Failed,
}
